# Generated by Django 5.2.12 on 2026-05-26 19:52

import leave.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_holiday_cities_holiday_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=leave.models.leave_attachment_path, verbose_name='Atestado / Documento'),
        ),
    ]
