# Generated by Django 5.2.12 on 2026-05-28 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_location_capacity'),
        ('leave', '0007_alter_leaverequest_attachment'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='holiday_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'date'], name='leave_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'status'], name='leave_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='leavereq_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'date_applied'], name='leavereq_emp_date_idx'),
        ),
    ]
