# Generated by Django 5.2.12 on 2026-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_emailconfiguration_backend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Código interno (ex: event_invitation)', max_length=100, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Comunicação')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto do E-mail')),
                ('body_html', models.TextField(verbose_name='Corpo (HTML)')),
                ('body_text', models.TextField(blank=True, null=True, verbose_name='Corpo (Texto Simples)')),
                ('variables_help', models.TextField(blank=True, help_text='Referência das variáveis que podem ser usadas neste template.', null=True, verbose_name='Variáveis Disponíveis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de E-mail',
                'verbose_name_plural': 'Templates de E-mail',
            },
        ),
    ]
