# Generated by Django 5.2.12 on 2026-05-21 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField(help_text='Armazena o access_token, refresh_token, token_uri, client_id, etc.')),
                ('calendar_id', models.CharField(blank=True, help_text='ID da agenda exclusiva criada para as escalas', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integração Google',
                'verbose_name_plural': 'Integrações Google',
            },
        ),
    ]
