# Generated by Django 5.2.12 on 2026-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_googleintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemoduleaccess',
            name='agenda',
            field=models.BooleanField(default=True, verbose_name='Agenda Corporativa'),
        ),
    ]
