# Generated by Django 5.2.12 on 2026-06-05 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rolemoduleaccess_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangeuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Bloqueados'),
        ),
    ]
