# Generated by Django 5.2.12 on 2026-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_orangeuser_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangeuser',
            name='is_netgram_suspended',
            field=models.BooleanField(default=False, help_text='Indica se o usuário está suspenso de utilizar a rede social interna (Netgram).', verbose_name='Acesso ao Netgram Suspenso'),
        ),
    ]
