# Generated by Django 5.2.12 on 2026-06-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0009_location_is_meeting_room'),
        ('agenda', '0006_add_cancellation_reason'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/Celular')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Currículo (CV)')),
                ('current_stage', models.CharField(choices=[('screening', 'Triagem'), ('hr_interview', 'Entrevista de RH'), ('tech_test', 'Teste Técnico'), ('manager_interview', 'Entrevista com Gestor'), ('proposal', 'Proposta/Contratação')], default='screening', max_length=50, verbose_name='Etapa Atual')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('HIRED', 'Contratado'), ('REJECTED', 'Reprovado')], default='IN_PROGRESS', max_length=20, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('hr_interview', 'Entrevista de RH'), ('tech_test', 'Teste Técnico'), ('manager_interview', 'Entrevista com Gestor')], max_length=50, verbose_name='Etapa da Entrevista')),
                ('date', models.DateTimeField(verbose_name='Data/Hora Agendada')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Instruções/Pauta')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('COMPLETED', 'Realizada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.candidate', verbose_name='Candidato')),
                ('interviewers', models.ManyToManyField(related_name='recruitment_interviews', to='pim.employee', verbose_name='Entrevistadores')),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_interviews', to='agenda.event', verbose_name='Evento na Agenda')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Pontuação (1-5)')),
                ('feedback_text', models.TextField(verbose_name='Feedback / Parecer Técnico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recruitment.interview', verbose_name='Entrevista')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to='pim.employee', verbose_name='Entrevistador')),
            ],
            options={
                'verbose_name': 'Feedback de Entrevista',
                'verbose_name_plural': 'Feedbacks de Entrevista',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Vaga')),
                ('description', models.TextField(verbose_name='Descrição da Vaga')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Fechada/Preenchida')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.subunit', verbose_name='Setor/Departamento')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobopening', verbose_name='Vaga Pretendida'),
        ),
    ]
