# Generated by Django 5.2.12 on 2026-06-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('category', models.CharField(choices=[('tech', 'Tecnologia'), ('soft', 'Comportamental'), ('language', 'Idioma'), ('tool', 'Ferramenta / Software'), ('other', 'Outros')], default='tech', max_length=20, verbose_name='Categoria')),
                ('icon', models.CharField(blank=True, default='bi-star', max_length=60, verbose_name='Ícone Bootstrap')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_score',
            field=models.FloatField(default=0.0, verbose_name='Match Score (%)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='recruitment.skill', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='desired_skills',
            field=models.ManyToManyField(blank=True, related_name='desired_for_jobs', to='recruitment.skill', verbose_name='Skills Desejáveis'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_for_jobs', to='recruitment.skill', verbose_name='Skills Obrigatórias'),
        ),
        migrations.CreateModel(
            name='PublicApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('resume', models.FileField(blank=True, null=True, upload_to='public_resumes/', verbose_name='Currículo')),
                ('match_score', models.FloatField(default=0.0, verbose_name='Match Score (%)')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Análise'), ('ACCEPTED', 'Aceito → Pipeline'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('rh_notes', models.TextField(blank=True, verbose_name='Observações do RH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobopening', verbose_name='Vaga')),
                ('skills', models.ManyToManyField(blank=True, related_name='applications', to='recruitment.skill', verbose_name='Skills Declaradas')),
            ],
            options={
                'verbose_name': 'Candidatura Pública',
                'verbose_name_plural': 'Candidaturas Públicas',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('email', 'job_opening')},
            },
        ),
    ]
