# Generated by Django 5.2.12 on 2026-06-09 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_skill_candidate_linkedin_url_candidate_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='stage_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 9, 19, 40, 36, 496430, tzinfo=datetime.timezone.utc), verbose_name='Data de Atualização da Etapa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_stage',
            field=models.CharField(choices=[('screening', 'Triagem'), ('interview', 'Entrevista'), ('psych_test', 'Teste Psicológico'), ('practical_test', 'Teste Prático'), ('probation_45', 'Estágio 45 d'), ('probation_90', 'Estágio 90 d'), ('hired', 'Efetivação')], default='screening', max_length=50, verbose_name='Etapa Atual'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='stage',
            field=models.CharField(choices=[('interview', 'Entrevista'), ('psych_test', 'Teste Psicológico'), ('practical_test', 'Teste Prático')], max_length=50, verbose_name='Etapa da Entrevista'),
        ),
    ]
