# Generated by Django 5.2.12 on 2026-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidate_stage_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Reprovação'),
        ),
    ]
