# Generated by Django 5.2.12 on 2026-06-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_location_is_meeting_room'),
        ('recruitment', '0004_candidate_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.jobtitle', verbose_name='Cargo da Vaga'),
        ),
    ]
