# Generated by Django 5.2.12 on 2026-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_add_job_title_to_job_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='onboarded',
            field=models.BooleanField(default=False, verbose_name='Cadastro Criado no Sistema'),
        ),
    ]
