# Generated by Django 5.2.12 on 2026-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_add_onboarded_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de Vagas'),
        ),
    ]
