# Generated by Django 5.2.12 on 2026-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='allow_shift_swaps',
            field=models.BooleanField(default=False, verbose_name='Permitir Trocas de Turno'),
        ),
    ]
