# Generated by Django 5.2.12 on 2026-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_subunit_allow_shift_swaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Capacidade (Pessoas)'),
        ),
    ]
