# Generated by Django 5.2.12 on 2026-06-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_location_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_meeting_room',
            field=models.BooleanField(default=False, verbose_name='É Sala de Reunião'),
        ),
    ]
