# Generated by Django 5.2.12 on 2026-05-26 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0007_subunit_allow_shift_swaps'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('event_type', models.CharField(choices=[('reuniao', 'Reunião'), ('integracao', 'Integração'), ('entrevista', 'Entrevista'), ('treinamento', 'Treinamento'), ('visita_tecnica', 'Visita Técnica'), ('outro', 'Outro')], default='reuniao', max_length=50, verbose_name='Tipo de Evento')),
                ('start_date', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data/Hora de Término')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações/Pauta')),
                ('color', models.CharField(default='#3b82f6', max_length=10, verbose_name='Cor de Exibição')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.city', verbose_name='Cidade')),
                ('employees', models.ManyToManyField(blank=True, related_name='events', to='pim.employee', verbose_name='Participantes (Colaboradores)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.location', verbose_name='Localização')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='pim.employee', verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento da Agenda',
                'verbose_name_plural': 'Eventos da Agenda',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nota Sem Título', max_length=150, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Rápida',
                'verbose_name_plural': 'Notas Rápidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
