# Generated by Django 5.2.12 on 2026-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('color', models.CharField(default='#3b82f6', max_length=10, verbose_name='Cor de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Compromisso',
                'verbose_name_plural': 'Tipos de Compromisso',
                'ordering': ['name'],
            },
        ),
    ]
