# Generated by Django 5.2.12 on 2026-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_participants',
            field=models.TextField(blank=True, null=True, verbose_name='Participantes Externos (E-mails)'),
        ),
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da Reunião (Meet/Zoom)'),
        ),
    ]
