# Generated by Django 5.2.12 on 2026-05-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_event_external_participants_event_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='referenced_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_notes', to='agenda.event', verbose_name='Compromisso Referenciado'),
        ),
    ]
