# Generated by Django 5.2.12 on 2026-06-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_quicknote_referenced_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Não Repetir'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente')], default='none', max_length=10, verbose_name='Recorrência'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_children', to='agenda.event', verbose_name='Evento Pai (Recorrência)'),
        ),
    ]
