# Generated by Django 5.2.12 on 2026-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_event_recurrence_event_recurrence_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
