# Generated by Django 5.2.12 on 2026-06-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_location_capacity'),
        ('performance', '0004_alter_survey_end_date'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_leadership_survey',
            field=models.BooleanField(default=False, verbose_name='Pesquisa de Liderança'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_evaluations', to='admin_app.subunit', verbose_name='Setor/Departamento'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='evaluated_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_leadership_evaluations', to='pim.employee', verbose_name='Líder Avaliado'),
        ),
    ]
