# Generated by Django 5.2.12 on 2026-05-26 19:52

import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payslip_base_salary_remove_payslip_net_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.payslip_document_path, verbose_name='Arquivo PDF'),
        ),
    ]
