# Generated by Django 5.2.12 on 2026-05-26 19:52

import buzz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0005_bugreport_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=buzz.models.bug_screenshot_path, verbose_name='Captura de tela'),
        ),
        migrations.AlterField(
            model_name='bugreportscreenshot',
            name='image',
            field=models.ImageField(upload_to=buzz.models.bug_screenshot_item_path),
        ),
        migrations.AlterField(
            model_name='buzzphoto',
            name='photo',
            field=models.ImageField(upload_to=buzz.models.buzz_photo_path),
        ),
    ]
