# Generated by Django 5.2.12 on 2026-06-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0006_alter_bugreport_screenshot_and_more'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Publicação'), ('comment', 'Comentário')], max_length=10, verbose_name='Tipo de Conteúdo')),
                ('content_id', models.IntegerField(verbose_name='ID do Conteúdo')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo da Denúncia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('REVIEWING', 'Em análise'), ('RESOLVED', 'Resolvido — conteúdo removido'), ('DISMISSED', 'Arquivado — sem violação')], default='PENDING', max_length=20, verbose_name='Status')),
                ('moderator_note', models.TextField(blank=True, verbose_name='Nota do Moderador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Denúncia')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='pim.employee', verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denúncia de Conteúdo',
                'verbose_name_plural': 'Denúncias de Conteúdo',
                'ordering': ['-created_at'],
            },
        ),
    ]
