# Generated by Django 5.2.12 on 2026-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_add_attendance_record_employee_date_index'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['employee', 'start_date'], name='shiftassign_emp_start_idx'),
        ),
        migrations.AddIndex(
            model_name='workscheduleassignment',
            index=models.Index(fields=['employee', 'start_date'], name='wschedassign_emp_start_idx'),
        ),
    ]
