# Generated by Django 5.2.12 on 2026-05-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_add_performance_indexes'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_work_day', models.BooleanField(default=True)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('theo_minutes', models.FloatField(default=0)),
                ('source', models.CharField(default='default', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('tolerance_minutes', models.SmallIntegerField(default=15)),
                ('automatic_break_minutes', models.SmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='pim.employee')),
            ],
            options={
                'verbose_name': 'Resumo Diário de Trabalho',
                'verbose_name_plural': 'Resumos Diários de Trabalho',
                'indexes': [models.Index(fields=['employee', 'date'], name='dailyworksum_emp_date_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
