# Generated by Django 5.2.12 on 2026-05-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_add_daily_work_summary'),
        ('pim', '0006_employee_is_time_tracking_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('worked_minutes', models.IntegerField(default=0)),
                ('expected_minutes', models.IntegerField(default=0)),
                ('balance_minutes', models.IntegerField(default=0)),
                ('extra_minutes', models.IntegerField(default=0)),
                ('deficit_minutes', models.IntegerField(default=0)),
                ('days_worked', models.SmallIntegerField(default=0)),
                ('late_days', models.SmallIntegerField(default=0)),
                ('absence_days', models.SmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='pim.employee')),
            ],
            options={
                'verbose_name': 'Resumo Mensal de Presenca',
                'verbose_name_plural': 'Resumos Mensais de Presenca',
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='monthlyattsum_emp_ym_idx')],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
